/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CpNavBar: typeof import('./src/components/CpNavBar.vue')['default']
    ElButtom: typeof import('element-plus/es')['ElButtom']
    ElButtomm: typeof import('element-plus/es')['ElButtomm']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCpNavBar: typeof import('element-plus/es')['ElCpNavBar']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElNavBar: typeof import('element-plus/es')['ElNavBar']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRow: (typeof import('element-plus/es'))['ElRow']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
